language: node_js
node_js:
  - "8"
before_install:
  - npm install -g serverless
jobs:
  include:
    - stage: tests
      script: npm run test
    - stage: tests
      script: npm run lint
    - stage: deploy
      script: npm run deploy
